apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      nodeSelector:
        django: "true"
      containers:
      - name: django
        image: solseek02/mydjango:latest
        ports:
        - containerPort: 8000
        env:
        - name: DEEPSEEK_API_URL
          value: "http://deepseek-svc:11434/api/generate"
        - name: JANUS_PRO_URL
          value: "https://myjanus-route-default.apps.rosa.hong.qg5f.p3.openshiftapps.com"
        - name: DJANGO_SETTINGS_MODULE
          value: "myproject.settings"
        - name: PYTHONUNBUFFERED
          value: "1"
        command: ["/bin/sh", "-c"]
        args:
        - |
          python manage.py migrate
          python manage.py runserver 0.0.0.0:8000
---
apiVersion: v1
kind: Service
metadata:
  name: django-svc
spec:
  selector:
    app: django
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP 